### PR TITLE
Add a map!

### PR DESCRIPTION
**Pull request by geospatialem**
Add a map to the July event using a Gist. Added some markup to make the event information stand out.

### CODE REVIEW

**Comment by tap-map** [comment]
You beat me to it again!

**Comment by fawcett** [comment]
Kitty, it looks like we aren't getting basemap tiles. Do you want me to revert, or do you have a fix?

**Comment by geospatialem** [comment]
@fawcett It's really temperamental... :dizzy_face: I noticed if you click the popup on, the tiles show up. I kinda like it there, but I'll let you decide. :stuck_out_tongue_winking_eye:

**Comment by geospatialem** [comment]
Put the question out to the Twittersphere :penguin:  (https://twitter.com/GeospatialEM/status/620779291911962624). We'll see if anyone bites!

**Comment by fawcett** [comment]
I am looking at it too.  It is weird that even on the Gist page, the tiles don't show at first, but it passes on geojsonlint.

**Comment by geospatialem** [comment]
I noticed it's happening on [Maptime Toronto](http://maptime.io/toronto)'s maps, too. I'm guessing it's a GitHub bug (?)

capture

**Comment by fawcett** [comment]
I played with the geojson for a while, but couldn't get it to work with github tiles either.  

In the end, I threw together a quick Mapbox map to get something up there.  

Commit here:  https://github.com/maptime/msp/commit/8590cc918bc05c9bed8f8bb432262e5f74dd82ee

The weirdest one is a geojson file by Github's own Ben Balter, and it works fine... https://github.com/benbalter/dc-wifi-social/blob/master/bars.geojson

Sorry KH, not trying to step on your toes here...

**Comment by geospatialem** [comment]
No toe stepping happening at all! **Thank you** for putting together another map to make 'er happen! 

I'll continue investigation because let's be honest it'll irritate me until we find out what's going on.

Have a great night!!

**Pull request merged**
